spring:
  # Local Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/dbmaster
    username: dbmasteruser
    password:
    driver-class-name: org.postgresql.Driver

  # Disable OAuth2 for local development
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: "local"
            client-secret: "local"

  # Disable AI for local development
  ai:
    bedrock:
      converse:
        chat:
          enabled: false

# Use local Foosball API
foosball:
  api:
    base-url: http://localhost:8081
